# Generated by Django 5.2.15 on 2026-07-06 13:51

import django.db.models.deletion
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=reports.models.report_upload_path)),
                ('hospital', models.CharField(blank=True, max_length=150)),
                ('uploaded_date', models.DateField(auto_now_add=True)),
                ('raw_text', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_flags', models.JSONField(blank=True, default=list)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patients.patient')),
            ],
            options={
                'ordering': ['-uploaded_date'],
            },
        ),
    ]
