"""
Patient History Summarizer (hybrid approach)

New AI feature (not in the original 3 from PROJECT_PLAN.md) -- built for the
moment a doctor opens a patient's file during consultation and needs the
relevant history in a few seconds, not a full chart review.

Input:  patient_history (dict) shaped like the payload behind
        GET /api/patients/<id>/history/ in API_CONTRACT.md:
        {
            "patient_id": "PID000145",
            "name": "Riya Kapoor",
            "age": 24,
            "gender": "F",
            "blood_group": "O+",
            "allergies": "Penicillin",
            "past_diseases": ["Mild Anemia (2026)"],
            "reports": [{"report_type": "...", "date": "...", "ai_summary": "...", "flags": [...]}],
            "prescriptions": [{"date": "...", "medicines": [...], "notes": "...", "followup_date": "..."}],
            "appointments": [{"date": "...", "reason": "...", "status": "..."}]
        }

Output: {
    "summary": str,          # short narrative for the doctor to read before walking in
    "key_points": list[str], # bullet-style structured facts (always rule-based, never from the LLM)
    "flags": list[str],      # carried over from report flags + any newly-derived risk notes
}

Same hybrid split as report_summarizer.py: anything that must be exactly
correct (allergies, active medications, chronic conditions) is extracted with
plain Python from structured data, never generated by the model. Claude is
only used to turn already-correct structured facts into a readable narrative.
"""

import json

from utils.claude_client import get_narrative


def _most_recent(items: list, date_key: str = "date") -> dict | None:
    if not items:
        return None
    return sorted(items, key=lambda x: x.get(date_key, ""), reverse=True)[0]


def extract_key_points(patient_history: dict) -> dict:
    """Stage 1: deterministic extraction of the facts a doctor most needs
    before consultation. Returns a structured dict; nothing here is generated
    text, just pulled/aggregated straight from the input."""
    allergies = patient_history.get("allergies") or "None known"
    chronic_conditions = patient_history.get("past_diseases", [])

    latest_rx = _most_recent(patient_history.get("prescriptions", []))
    active_medications = latest_rx.get("medicines", []) if latest_rx else []

    all_report_flags = []
    for report in patient_history.get("reports", []):
        for flag in report.get("flags", []):
            if flag not in all_report_flags:
                all_report_flags.append(flag)

    recent_appointments = sorted(
        patient_history.get("appointments", []), key=lambda a: a.get("date", ""), reverse=True
    )[:3]

    return {
        "allergies": allergies,
        "chronic_conditions": chronic_conditions,
        "active_medications": active_medications,
        "report_flags": all_report_flags,
        "recent_appointments": recent_appointments,
        "latest_followup_date": latest_rx.get("followup_date") if latest_rx else None,
    }


def build_key_points_list(extracted: dict) -> list:
    """Turn the extracted dict into plain bullet strings for the UI -- kept
    separate from the narrative so the UI can always show these even if the
    Claude API call fails."""
    points = [f"Allergies: {extracted['allergies']}"]
    if extracted["chronic_conditions"]:
        points.append("Chronic/past conditions: " + ", ".join(extracted["chronic_conditions"]))
    if extracted["active_medications"]:
        meds = ", ".join(m.get("name", "?") for m in extracted["active_medications"])
        points.append(f"Currently prescribed: {meds}")
    if extracted["report_flags"]:
        points.append("Flagged report findings: " + "; ".join(extracted["report_flags"]))
    if extracted["latest_followup_date"]:
        points.append(f"Follow-up due: {extracted['latest_followup_date']}")
    return points


def _fallback_summary(patient_history: dict, extracted: dict) -> str:
    name = patient_history.get("name", "This patient")
    age = patient_history.get("age", "unknown age")
    parts = [f"{name}, {age}."]
    if extracted["allergies"] != "None known":
        parts.append(f"Allergic to {extracted['allergies']}.")
    if extracted["chronic_conditions"]:
        parts.append("History of " + ", ".join(extracted["chronic_conditions"]) + ".")
    if extracted["report_flags"]:
        parts.append("Recent flagged findings: " + "; ".join(extracted["report_flags"]) + ".")
    if extracted["active_medications"]:
        meds = ", ".join(m.get("name", "?") for m in extracted["active_medications"])
        parts.append(f"Currently on {meds}.")
    return " ".join(parts)


SYSTEM_PROMPT = (
    "You are a clinical summarization assistant preparing a doctor for an "
    "upcoming consultation. You are given ALREADY-VERIFIED structured facts "
    "(allergies, conditions, medications, flagged report findings) -- never "
    "invent, infer, or add any fact not present in the input. Write a tight "
    "3-4 sentence handoff note a doctor could read in 10 seconds while "
    "walking into the room. Lead with anything safety-critical (allergies, "
    "concerning flags), then chronic conditions and current medications. "
    "Do not suggest a diagnosis or treatment -- this is a history recap only."
)


def summarize_patient_history(patient_history: dict) -> dict:
    extracted = extract_key_points(patient_history)
    key_points = build_key_points_list(extracted)

    user_prompt = (
        f"Patient: {patient_history.get('name', 'Unknown')}, "
        f"{patient_history.get('age', '?')} y/o {patient_history.get('gender', '')}\n"
        f"Structured facts: {json.dumps(extracted, default=str)}\n\n"
        "Write the consultation handoff note now."
    )
    narrative = get_narrative(SYSTEM_PROMPT, user_prompt, max_tokens=300)
    summary = narrative if narrative else _fallback_summary(patient_history, extracted)

    return {"summary": summary, "key_points": key_points, "flags": extracted["report_flags"]}


if __name__ == "__main__":
    sample_history = {
        "patient_id": "PID000145",
        "name": "Riya Kapoor",
        "age": 24,
        "gender": "F",
        "allergies": "Penicillin",
        "past_diseases": ["Mild Anemia (2026)"],
        "reports": [
            {"report_type": "Blood Test (CBC)", "date": "2026-06-20",
             "flags": ["Low Hemoglobin (11.0 g/dL, normal range 12.0-16.5)"]},
        ],
        "prescriptions": [
            {"date": "2026-06-20", "medicines": [{"name": "Ferrous Sulfate", "dosage": "325mg"}],
             "followup_date": "2026-07-20"},
        ],
        "appointments": [{"date": "2026-06-20", "reason": "General checkup", "status": "completed"}],
    }
    print(json.dumps(summarize_patient_history(sample_history), indent=2))
