# Generated by Django 5.2.15 on 2026-07-06 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('available_days', models.JSONField(default=list, help_text='e.g. ["Mon", "Wed", "Fri"]')),
                ('visiting_hours', models.CharField(blank=True, max_length=50)),
                ('is_approved', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/doctors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
